2019-08-27 19:42:24,194 ERROR: Exception on /auth/login [GET] [in /home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thevidvid/microblog/app/auth/routes.py", line 29, in login
    return render_template('login.html', title=_('Sign-in'), form=form)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2019-08-27 19:42:29,074 ERROR: Exception on /auth/login [GET] [in /home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thevidvid/microblog/app/auth/routes.py", line 29, in login
    return render_template('login.html', title=_('Sign-in'), form=form)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2019-08-27 19:42:30,745 ERROR: Exception on /auth/login [GET] [in /home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thevidvid/microblog/app/auth/routes.py", line 29, in login
    return render_template('login.html', title=_('Sign-in'), form=form)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2019-08-27 19:49:42,581 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:75]
