2019-08-15 20:55:14,169 ERROR: Exception on /index [GET] [in /home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/thevidvid/microblog/app/routes.py", line 31, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thevidvid/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/thevidvid/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock content %}
  File "/home/thevidvid/microblog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-08-15 21:11:54,543 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 21:14:57,561 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 21:21:56,985 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 21:26:29,694 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 21:28:54,454 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 21:30:29,055 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 07:51:15,811 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 08:48:24,706 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 11:30:55,413 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 11:37:17,841 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 11:52:35,972 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 12:13:01,697 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 18:31:06,673 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 18:34:51,083 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-16 18:45:18,777 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-17 11:02:33,592 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-17 11:26:59,613 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-17 11:31:22,154 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-17 11:48:03,587 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
2019-08-17 12:01:07,553 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
2019-08-17 12:45:53,002 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
2019-08-17 17:24:57,943 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
2019-08-18 12:21:15,748 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
2019-08-18 14:21:32,975 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
2019-08-18 14:24:29,349 ERROR: Exception on /reset_password_request [GET] [in /home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thevidvid/microblog/app/routes.py", line 98, in reset_password_request
    title='Reset Password', form=form)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thevidvid/microblog/app/templates/reset_password_request.html", line 15, in template
    {{ form.submit() }}
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-08-18 14:28:18,040 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:46]
